export const USERS_RETRIEVED = "USER/USERS_RETRIEVED";
export const USER_SELECTED = "USER/USER_SELECTED";
export const USER_ADDED = "USER/USER_SELECTED";
export const USER_UPDATED = "USER/USER_SELECTED";
export const USER_LOADING = "USER/USER_LOADING";
export const USER_MODAL_CLOSE = "USER/USER_MODAL_CLOSE";
export const USER_DELETE = "USER/USER_DELETE";
